(cl:defpackage interface-srv
  (:use )
  (:export
   "CONVERTER"
   "<CONVERTER-REQUEST>"
   "CONVERTER-REQUEST"
   "<CONVERTER-RESPONSE>"
   "CONVERTER-RESPONSE"
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "PARAMETER"
   "<PARAMETER-REQUEST>"
   "PARAMETER-REQUEST"
   "<PARAMETER-RESPONSE>"
   "PARAMETER-RESPONSE"
  ))

