/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/wqh/catkin_ws/src/interface/srv/KeepStaticParameter.srv
 *
 */


#ifndef INTERFACE_MESSAGE_KEEPSTATICPARAMETER_H
#define INTERFACE_MESSAGE_KEEPSTATICPARAMETER_H

#include <ros/service_traits.h>


#include <interface/KeepStaticParameterRequest.h>
#include <interface/KeepStaticParameterResponse.h>


namespace interface
{

struct KeepStaticParameter
{

typedef KeepStaticParameterRequest Request;
typedef KeepStaticParameterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct KeepStaticParameter
} // namespace interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interface::KeepStaticParameter > {
  static const char* value()
  {
    return "2bf5219bbb63705278c4859ab89c4529";
  }

  static const char* value(const ::interface::KeepStaticParameter&) { return value(); }
};

template<>
struct DataType< ::interface::KeepStaticParameter > {
  static const char* value()
  {
    return "interface/KeepStaticParameter";
  }

  static const char* value(const ::interface::KeepStaticParameter&) { return value(); }
};


// service_traits::MD5Sum< ::interface::KeepStaticParameterRequest> should match 
// service_traits::MD5Sum< ::interface::KeepStaticParameter > 
template<>
struct MD5Sum< ::interface::KeepStaticParameterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interface::KeepStaticParameter >::value();
  }
  static const char* value(const ::interface::KeepStaticParameterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interface::KeepStaticParameterRequest> should match 
// service_traits::DataType< ::interface::KeepStaticParameter > 
template<>
struct DataType< ::interface::KeepStaticParameterRequest>
{
  static const char* value()
  {
    return DataType< ::interface::KeepStaticParameter >::value();
  }
  static const char* value(const ::interface::KeepStaticParameterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interface::KeepStaticParameterResponse> should match 
// service_traits::MD5Sum< ::interface::KeepStaticParameter > 
template<>
struct MD5Sum< ::interface::KeepStaticParameterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interface::KeepStaticParameter >::value();
  }
  static const char* value(const ::interface::KeepStaticParameterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interface::KeepStaticParameterResponse> should match 
// service_traits::DataType< ::interface::KeepStaticParameter > 
template<>
struct DataType< ::interface::KeepStaticParameterResponse>
{
  static const char* value()
  {
    return DataType< ::interface::KeepStaticParameter >::value();
  }
  static const char* value(const ::interface::KeepStaticParameterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERFACE_MESSAGE_KEEPSTATICPARAMETER_H
